language: python
sudo: true
env:
  - TOXENV=py34
  - TOXENV=py27
install:
  - travis_retry pip install codecov
  - travis_retry pip install tox
script:
  - travis_retry tox -- --concurrency=5
after_success:
    codecov